

def add(a, b):
    return a+b    # ...


def main():
    a = int(input('Enter 1st number : '))  # ...
    b = int(input('Enter 2nd number : '))  # ...

    c = add(a, b)
    print('Sum of %d,%d is %d' % (a,b,c))  # ...
main()